[package]
name = "carescanner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
futures = "0.3.31"
governor = "0.10.0"
tokio = { version = "1.45.1", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
